blank_issues_enabled: true
contact_links:
- name: Question
  url: 'https://github.com/TheAwiteb/frenamer/discussions/new?category=question'
  about: Ask a question about frenamer in the discussions section

- name: Feature Request
  url: 'https://github.com/TheAwiteb/frenamer/discussions/new?category=feature-request'
  about: If you think that the frenamer needs a new feature, you can tell us about it in the discussions section